# Generated by Django 5.2.1 on 2025-11-13 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BookingLead",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("phone", models.CharField(max_length=30)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("preferred_date", models.CharField(blank=True, max_length=50)),
                ("message", models.TextField(blank=True)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("landing", "Landing Page"),
                            ("site", "Website"),
                            ("other", "Other"),
                        ],
                        default="landing",
                        max_length=30,
                    ),
                ),
                ("landing_slug", models.CharField(blank=True, max_length=120)),
                ("utm", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("notified", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="SocialLanding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(max_length=120, unique=True)),
                ("title", models.CharField(max_length=220)),
                ("subtitle", models.CharField(blank=True, max_length=300)),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="landing_images/"
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("badge_text", models.CharField(blank=True, max_length=80)),
                (
                    "cta_text",
                    models.CharField(default="Book Appointment", max_length=80),
                ),
                (
                    "cta_url",
                    models.URLField(
                        blank=True, help_text="Optional external booking URL"
                    ),
                ),
                (
                    "whatsapp_number",
                    models.CharField(
                        blank=True, help_text="E.g. 9197020724751", max_length=20
                    ),
                ),
                ("whatsapp_message", models.CharField(blank=True, max_length=350)),
                ("phone", models.CharField(blank=True, max_length=30)),
                ("small_note", models.CharField(blank=True, max_length=250)),
                (
                    "offer_points",
                    models.TextField(blank=True, help_text="One per line"),
                ),
                (
                    "testimonials",
                    models.TextField(blank=True, help_text="One per line or JSON"),
                ),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
