# Generated by Django 5.2.1 on 2025-11-13 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_bookinglead_sociallanding"),
    ]

    operations = [
        migrations.RenameField(
            model_name="sociallanding",
            old_name="image",
            new_name="hero_image",
        ),
        migrations.RenameField(
            model_name="sociallanding",
            old_name="description",
            new_name="testimonial_1_review",
        ),
        migrations.RemoveField(
            model_name="sociallanding",
            name="active",
        ),
        migrations.RemoveField(
            model_name="sociallanding",
            name="badge_text",
        ),
        migrations.RemoveField(
            model_name="sociallanding",
            name="cta_text",
        ),
        migrations.RemoveField(
            model_name="sociallanding",
            name="cta_url",
        ),
        migrations.RemoveField(
            model_name="sociallanding",
            name="offer_points",
        ),
        migrations.RemoveField(
            model_name="sociallanding",
            name="small_note",
        ),
        migrations.RemoveField(
            model_name="sociallanding",
            name="testimonials",
        ),
        migrations.RemoveField(
            model_name="sociallanding",
            name="whatsapp_number",
        ),
        migrations.AddField(
            model_name="sociallanding",
            name="result_image",
            field=models.ImageField(blank=True, null=True, upload_to="landing_images/"),
        ),
        migrations.AddField(
            model_name="sociallanding",
            name="result_title",
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name="sociallanding",
            name="testimonial_1_name",
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name="sociallanding",
            name="testimonial_2_name",
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name="sociallanding",
            name="testimonial_2_review",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="sociallanding",
            name="testimonial_3_name",
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name="sociallanding",
            name="testimonial_3_review",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="sociallanding",
            name="video",
            field=models.FileField(blank=True, null=True, upload_to="videos/"),
        ),
        migrations.AddField(
            model_name="sociallanding",
            name="video_description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="sociallanding",
            name="video_title",
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
