# Generated by Django 5.2.1 on 2025-11-13 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_rename_image_sociallanding_hero_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sociallanding",
            name="active",
            field=models.BooleanField(default=True),
        ),
    ]
