# Generated by Django 5.2.1 on 2026-01-05 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_sociallanding_active"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClinicHoliday",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "closed_slot",
                    models.CharField(
                        choices=[
                            ("full", "Full Day Closed"),
                            ("morning", "Morning Closed"),
                            ("evening", "Evening Closed"),
                        ],
                        default="full",
                        max_length=10,
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=100)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["date"],
                "unique_together": {("date", "closed_slot")},
            },
        ),
    ]
