# Generated by Django 5.2.1 on 2026-01-15 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_clinicholiday"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="appointment",
            options={"ordering": ["appointment_date", "appointment_time"]},
        ),
        migrations.AddConstraint(
            model_name="appointment",
            constraint=models.UniqueConstraint(
                fields=("appointment_date", "appointment_time"), name="unique_time_slot"
            ),
        ),
    ]
