# Generated by Django 5.2.1 on 2026-01-27 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0006_alter_appointment_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="HairWellnessReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("patient_name", models.CharField(max_length=100)),
                ("age", models.IntegerField(blank=True, null=True)),
                ("gender", models.CharField(blank=True, max_length=10, null=True)),
                ("contact", models.CharField(blank=True, max_length=20, null=True)),
                ("subtotal_a", models.IntegerField()),
                ("subtotal_b", models.IntegerField()),
                ("subtotal_c", models.IntegerField()),
                ("subtotal_e", models.IntegerField()),
                ("total_score", models.IntegerField()),
                ("status", models.CharField(max_length=50)),
                ("phase", models.CharField(max_length=150)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
