# Generated by Django 5.2.1 on 2026-02-15 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0007_hairwellnessreport"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="visit_status",
            field=models.CharField(
                choices=[
                    ("booked", "Booked"),
                    ("visited", "Visited"),
                    ("cancelled", "Cancelled"),
                    ("unvisited", "Unvisited"),
                ],
                default="booked",
                max_length=15,
            ),
        ),
    ]
