# Generated by Django 5.2.1 on 2026-02-28 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0008_appointment_visit_status"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="appointment",
            options={"ordering": ["-appointment_date", "-appointment_time"]},
        ),
        migrations.AddField(
            model_name="appointment",
            name="booking_id",
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
