# Generated by Django 5.2.1 on 2026-02-28 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0009_alter_appointment_options_appointment_booking_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="appointment",
            name="booking_id",
        ),
    ]
