# Generated by Django 5.2.1 on 2026-02-28 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0010_remove_appointment_booking_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="booking_id",
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
