# Generated by Django 5.2.1 on 2026-06-02 09:54

import app.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0011_appointment_booking_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="TestPatient",
            fields=[
                (
                    "patient_id",
                    models.CharField(
                        default=app.models.test_generate_patient_id,
                        editable=False,
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(blank=True, max_length=100, null=True)),
                ("dob", models.DateField()),
                ("gender", models.CharField(max_length=20)),
                ("contact_number", models.CharField(max_length=15)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name="appointment",
            name="patient_type",
            field=models.CharField(
                choices=[("new", "New Patient"), ("existing", "Follow-up")],
                max_length=10,
            ),
        ),
        migrations.CreateModel(
            name="TestAppointment",
            fields=[
                (
                    "appointment_id",
                    models.CharField(
                        editable=False, max_length=20, primary_key=True, serialize=False
                    ),
                ),
                ("disease", models.CharField(max_length=255)),
                ("appointment_date", models.DateField()),
                ("appointment_time", models.TimeField()),
                (
                    "visit_status",
                    models.CharField(
                        choices=[
                            ("booked", "Booked"),
                            ("checked_in", "Checked In"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="booked",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="appointments",
                        to="app.testpatient",
                    ),
                ),
            ],
        ),
    ]
